export type AppStackParamList = {
  Login: undefined;
  Promotion: undefined;
  ForgotPassword: undefined;
  ForgotPasswordNext: undefined;
  Register: undefined;
  RegisterNext: undefined;
  MainMenu: undefined;
  Contact: undefined;
  Profile: undefined;
  About: undefined;
  BireyselSiparis: undefined;
  BireyselOnKabul: undefined;
  KargoTakip: undefined;
  EnYakinPtt: undefined;
  PostaKodu: undefined;
  GonderiHesapla: undefined;
  EnYakinKargomat: undefined;
  KargomatGonderileri: undefined;
  KargomatHakkinda: undefined;
  NasilKullanirim: undefined;
  aldigimUrunler: undefined;
  dahaFazla: undefined;
  duyurular: undefined;
  filatelikUrunler: undefined;
  telgrafIslemleri: undefined;
  dahaFazlaTelgraf: undefined;
};
